// Generated by Xata Codegen 0.29.1. Please do not edit.
import { buildClient } from "@xata.io/client";
/** @typedef { import('./types').SchemaTables } SchemaTables */
/** @type { SchemaTables } */
const tables = [
  {
    name: "tag",
    columns: [
      { name: "name", type: "string", notNull: true, defaultValue: "gallery" },
    ],
    revLinks: [{ column: "tag", table: "tag-to-image" }],
  },
  {
    name: "image",
    columns: [
      { name: "name", type: "string", notNull: true, defaultValue: "Image" },
      { name: "image", type: "file" },
    ],
    revLinks: [{ column: "image", table: "tag-to-image" }],
  },
  {
    name: "tag-to-image",
    columns: [
      { name: "image", type: "link", link: { table: "image" } },
      { name: "tag", type: "link", link: { table: "tag" } },
    ],
  },
  { name: "demo", columns: [] },
  {
    name: "nguoi_dung",
    columns: [
      { name: "email", type: "string" },
      { name: "mat_khau", type: "string" },
      { name: "ho_ten", type: "string" },
      { name: "anh_dai_dien", type: "string" },
      { name: "tuoi", type: "int" },
      { name: "ngay_sinh", type: "datetime" },
    ],
    revLinks: [
      { column: "nguoi_dung", table: "hinh_anh" },
      { column: "nguoi_dung", table: "luu_anh" },
      { column: "nguoi_dung", table: "binh_luan" },
    ],
  },
  {
    name: "hinh_anh",
    columns: [
      { name: "ten_hinh", type: "string" },
      { name: "duong_dan", type: "string" },
      { name: "mo_ta", type: "string" },
      { name: "nguoi_dung", type: "link", link: { table: "nguoi_dung" } },
    ],
    revLinks: [
      { column: "hinh_anh", table: "luu_anh" },
      { column: "hinh_anh", table: "binh_luan" },
    ],
  },
  {
    name: "luu_anh",
    columns: [
      { name: "ngay_luu", type: "datetime" },
      { name: "nguoi_dung", type: "link", link: { table: "nguoi_dung" } },
      { name: "hinh_anh", type: "link", link: { table: "hinh_anh" } },
    ],
  },
  {
    name: "binh_luan",
    columns: [
      { name: "nguoi_dung", type: "link", link: { table: "nguoi_dung" } },
      { name: "ngay_binh_luan", type: "datetime" },
      { name: "hinh_anh", type: "link", link: { table: "hinh_anh" } },
      { name: "noi_dung", type: "string" },
    ],
  },
];
/** @type { import('@xata.io/client').ClientConstructor<{}> } */
const DatabaseClient = buildClient();
const defaultOptions = {
  databaseURL:
    "https://Long-Phan-Quang-Minh-s-workspace-kvk057.ap-southeast-2.xata.sh/db/picturest",
};
/** @typedef { import('./types').DatabaseSchema } DatabaseSchema */
/** @extends DatabaseClient<DatabaseSchema> */
export class XataClient extends DatabaseClient {
  constructor(options) {
    super({ ...defaultOptions, ...options }, tables);
  }
}
let instance = undefined;
/** @type { () => XataClient } */
export const getXataClient = () => {
  if (instance) return instance;
  instance = new XataClient();
  return instance;
};
